---
title: "Statisztika 1. szeminárium"
output: html_document
---

## 2023/2024. tavaszi félév
## PPKE-BTK


***

<style>
  
  p {
    line-height: 1.5;
  }
  strong {
    color: #a82727;
  }
</style>

## Tantárgy célja   
  
A szeminárium a Statisztika 1. előadáshoz kapcsolódik. Célja az előadáson tanultak gyakorlása és elmélyítése, a legfontosabb statisztikák és hipotézisvizsgálati módszerek megismerése. Az első negyedévben a valószínűségszámítással, a második negyedévben pedig a statisztika alapjaival (leíró statisztikák, becsléselmélet, hipotézisvizsgálat alapjai) foglalkozunk.

**TRIGGER WARNING**  

A szemináriumon sokat fogunk számolni, ezért érdemes **számológépet** beszerezni vagy találni egy jó számológép alkalmazást a telefonjukra.  

## A félév felépítése  

1. negyedév: Valószínűségszámítás: műveletek, feltételes valószínűségek, valószínűségi változók  
2. negyedév: Statisztika alapok: leíró statisztika, becsléselmélet, hipotézisvizsgálat (várható értékre vonatkozó próbák)  
  

## Segédanyagok  
  
A hallgatók az órán tanultak elmélyítésére, begyakorlására házi gyakorló feladatokat kapnak. Ezek megoldása nem kötelező a félév teljesítéséhez, de jó visszajelzés lehet a hallgatóknak, hogy sikerült-e elsajátítani a tanultakat, és nekem is. A zárthelyi dolgozat csak olyan feladattípusokat tartalmaz, amelyekre az órán is kitérünk, és a gyakorló feladatsorokban előfordultak.  

A félév során a segédanyagokat, házi feladatsorokat, illetve azok megoldásait elsősorban e-mailben kapják meg a hallgatók. A honlapon egyes témákban írt összefoglalókat találnak, illetve a szemináriumon is használt diasorokat.  

A ZH-n minden segédanyag (gyakorló feladatsorok megoldásai, online összefoglalók, órai jegyzetek, vagy azok alapján készített puskák) szabadon használható. Képletgyűjteményt a hallgatók tőlem is kapnak, vagy saját példányt nyomtathatnak, amennyiben nagyobb méretben szeretnék használni, vagy megjegyzésekkel, jegyzetekkel kívánják ellátni.  
 

## A félév teljesítése
  
A hallgatók a félév végén gyakorlati jegyet kapnak. Ez a félév során, az előre egyeztetett időpontban megírt **két zárthelyi dolgozat összesített ponteredményétől** függ.  

A félév teljesítésének feltétele, hogy a hallgató **mindkét** ZH-jának eredménye **legalább elégséges**. A nem megírt ZH elégtelennek minősül. Indokolt esetben (pl. betegség esetén) lehetőség van a ZH pótlására. A távolmaradást a hallgató a ZH időpontja előtt köteles jelezni.  

A sikertelen ZH javítására a félév végén, előre egyeztetett időpontban és módon van lehetőség.  

**A ZH-k várható időpontjai a 2023/24. tavaszi félévben:**
  
**I. ZH:** 2023.04.02.   
**II. ZH:** 2023.05.21.  
  

A ZH-n használhatják az órai jegyzeteiket, illetve a kapott segédanyagokat (eloszlás-táblázatok, képletgyűjtemények, összefoglalók, házi feladatok megoldásai, stb.)

