---
title: "Műveletek valószínűségekkel"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Alapfogalmak

- Kísérlet: a jelenség, amit megfigyelünk, azonos körülmények között megismételhető (pl. kockadobás, kártyahúzás, céltáblára lövés, aktuális időjárás, stb.), általában véletlen kísérletekről van szó, vagyis a kimenetele a véletlentől függ
- Kimenetelek: a kísérlet lehetséges eredményei
- Eseménytér: a kimenetelek halmaza, másképpen az elemi események halmaza (pl. kockadobásnál az összes lehetőség)
- Események: az eseménytér részhalmazai. Lehetnek elemik és összetettek. 
- Elemi esemény: tovább már nem bontható, csak egyféleképpen következhet be (pl. 3-ast dobunk)
- Összetett esemény: felbonthatók, több elemi eseményből állnak, azok halmazai (pl. páros számot dobunk)
- Esemény bekövetkezése: egy esemény bekövetkezik, ha a megfigyelt kimenetel eleme az adott halmaznak.
- Valószínűség: az eseményekhez rendelhető valós, 0 és 1 közötti szám, amely megadja hogy ha megismételjük a kísérletet, akkor az esetek milyen arányában következik be az adott esemény.
- Biztos esemény: amely biztosan bekövetkezik, valószínűsége 1 = 100%.
- Lehetetlen esemény: amely az adott kísérlet során nem következhet be, valószínűsége 0 = 0%.
- Klasszikus valószínűségi mező: az elemi események száma véges és ezek valószínűsége pozitív és egyenlő (pl. szabályos kockával végzett dobás)

## Példa: kártyahúzás

A kísérlet, amit végzünk legyen, hogy egy megkevert 32 lapos magyar kártyapakliból véletlenszerűen húzunk egy lapot.  

A magyar kártyapakli 32 lapból áll: 4 színből (piros, zöld, makk és tök), színenként 8-8 lapból, amelyekből 4-4 számos (7-től 10-ig) és 4-4 figurás (alsó, felső, király, ász).  

A kísérlet elemi eseményei az egyes konkrét kártyalapok: pl. piros 7-es, makk ász, tök felső, stb.  
Az eseménytér tehát 32 elemi eseményből áll össze, mivel ennyi kártyalap van.  
Összetett események lehetnek, hogy például pirosat húzunk (8 elemi esemény), alsót húzunk (4 elemi esemény), számos lapot húzunk (16 elemi esemény).  
A kártyahúzás esetében véges számú elemi eseményről van szó, és mivel mindegyik lap kihúzásának ugyanannyi a valószínűsége, klassszikus valószínűségi mezőről beszélhetünk.  

Ebben az esetben az egyes események valószínűsége kiszámítható:  
$$P(A) = \frac{\text{kedvező elemi események száma}}{\text{összes elemi esemény száma}}$$

A fentiek alapján mit mondhatunk arról, mennyi annak a valószínűsége, hogy a pakliból zöld lapot húzunk?  

Mivel 8 zöld lap van összesen, a valószínűség: $P(Z)=\frac{8}{32}=\frac{1}{4}=0.25=25\%$  
Ugyanígy annak, hogy (miután visszatettük a húzott lapot) pirosat húzunk, a valószínűsége: $P(P)=\frac{8}{32}=\frac{1}{4}$  
Annak, hogy figurás lapot húzunk (összesen $4*4=16$ ilyen van) pedig $P(F)=\frac{16}{32}=\frac{1}{2}=50\%$  

## Elemi műveletek 

### 1. Komplementer

Az első művelet, amit megnézünk, a komplementer esemény valószínűsége.  
Komplementer eseménynek nevezzük azt az eseményt, amely akkor és csak akkor valósul meg, ha az eredeti esemény nem. Így például komplementer a páros és páratlan szám. Ha egy szám páros, akkor nem páratlan, ha egy szám nem páros, akkor páratlan. Tehát, ha az egyik esemény nem következik be, akkor a komplementere bekövetkezik.  
A komplementer esemény valószínűségének jelölése és képlete: 
$$P(\bar{A})=1-P(A)$$

Mennyi a valószínűsége, hogy nem zöldet húzunk?  
Mivel $3*8 = 24$ nem zöld lap van: $P(\bar{Z})=\frac{24}{32}=0.75$  
De ezt úgy is megkaphatjuk, hogy $P(\bar{Z})=1-P(Z)=1-0.25=0.75$  

A komplementer esemény komplementere az eredeti esemény, ezért a valószínűsége is:  
$$P(\bar{\bar{A}})=P(A)$$

### 2. Események szorzata

Egy másik gyakori helyzet, amikor annak valószínűségét keressük, hogy két esemény együttesen bekövetkezik. Ezt jelöljük a két esemény szorzatával, tehát $P(A*B)$ azt jelöli, hogy az `A` és `B` esemény egyaránt megvalósul. Halmazelméleti fogalmakkal ez a halmazok metszetének felel meg. A szorzat kommutatív, $P(A*B)=P(B*A)$. Ezen túl kiterjeszthető több eseményre is: pl. $P(A*B*C)$ azt jelenti, hogy a három esemény együtt bekövetkezik.  

Mennyi a valószínűsége, hogy a húzott kártyalap egyszerre zöld és piros?  
Ebben az esetben nincs olyan kártyalap a pakliban, amely mindkét feltételnek megfelelne, hiszen minden kártyalapnak egyetlen színe van. A keresett valószínűség tehát:  
$$P(Z*P)=\frac{0}{32}=0$$

Az ilyen események egymást kölcsönösen kizárják, és valószínűségük 0.  

Mennyi a valószínűsége, hogy a húzott kártyalap egyszerre zöld és figurás?  
Itt nem egymást kizáró eseményekről van szó, hanem olyanokról, amelyek együttesen is bekövetkezhetnek. Összesen 4 figurás zöld lap van a pakliban (zöld alsó, felső, király és ász), ezért  
$$P(Z*F)=\frac{4}{32}=12,5\%$$

#### Szorzat valószínűségének határai

Az együttes bekövetkezésnek nincs általános képlete, kiszámításához további információra van szükség. Az eredeti két esemény valószínűségéből legfeljebb a szorzat határait tudjuk meghatározni:  

- A két esemény szorzatának valószínűsége nem lehet nagyobb a kisebb esemény valószínűségénél. Ez akkor van, ha a kevésbé valószínű esemény részhalmaza a valószínűbbnek. 
- A két esemény szorzatának valószínűsége akkor lehet 0, ha a két esemény valószínűségének összege $\le 1$.
- Ha a két esemény valószínűségének összege $\ge 1$, akkor a szorzat valószínűsége $P(A*B)\ge P(A)+P(B)-1$

### 3. Események összege

A másik gyakori eset, amikor annak valószínűségét keressük, hogy két (vagy több) esemény közül legalább az egyik megvalósul: A vagy B (vagy C, stb.) esemény bekövetkezik. Ebben az esetben megengedő vagyról van szó: az is jó, ha mindkét (több, mint egy) esemény valósul meg. Halmazelméleti fogalmakkal ez a halmazok uniójának felel meg. Jelölése $P(A+B)$ és ez a művelet is kommutatív, $P(A+B)=P(B+A)$ és kiterjeszthető több eseményre is.  

Mennyi a valószínűsége, hogy a húzott kártyalap zöld vagy piros?  
Ebben az esetben megfelel nekünk az összes zöld kártya (összesen 8) és az összes piros (szintén 8):  
$$P(Z+P)=\frac{16}{32}=50\%$$
Ha a két (vagy több) esemény **egymást kizáró**:  
$$P(A+B)=P(A)+P(B)$$

Mennyi a valószínűsége, hogy a húzott kártyalap zöld vagy figurás?  
Ebben az esetben megfelel nekünk az összes zöld lap (8 kártya) és ezen felül azok többi színből a figurás lapok (3-szor 4-4 kártya):  
$$P(Z+F)=\frac{8+3*4}{32}=\frac{20}{32}=62,5\%$$
Itt nem adhatjuk egyszerűen össze a két valószínűséget: $0,25 + 0,5 \ne 0,625$. Mégpedig azért nem, mert ha összeadnánk, lennének olyan esetek, amelyeket kétszer számolunk: a zöld figurás lapokat. Ezeknek a valószínűségét le kell vonnunk az összegből: $0,25+0,5-0,125=0,625$. 
Általánosan:  
$$P(A+B)=P(A)+P(B)-P(A*B)$$
Míg a korábbi képlet csak akkor működik, ha a két esemény kizáró, és ezért $P(A*B)=0$, ez utóbbi képlet minden esetben működik, és az abban szereplő 4 érték közül 3 ismeretében bármelyik hiányzó érték kiszámítható. Például a szorzat:   
$$P(A*B)=P(A)+P(B)-P(A+B)$$
Vagy az egyik esemény valószínűsége:  
$$P(A)=P(A+B)+P(A*B)-P(B)$$

#### Összeg valószínűségének határai  

Ezt a valószínűséget is csak akkor tudjuk kiszámítani, ha a P(A) és P(B) valószínűségek mellett egyéb információink is vannak. Csak P(A) és P(B) ismeretében legfeljebb az összeg valószínűségének határait tudjuk megállapítani:  
- Az összeg valószínűsége legalább a nagyobb valószínűségű esemény valószínűségével egyenlő, mégpedig akkor, ha a kevésbé valószínű esemény ennek részhalmaza.
- Legfeljebb 1 lehet, ha $P(A)+P(B)\ge 1$ és legfeljebb $P(A)+P(B)$, ha $P(A)+P(B)\le 1$.

### 4. Események különbsége

Végül az alapműveletek közül az utolsó annak valószínűsége, hogy az egyik esemény bekövetkezik, de a másik esemény nem. Ezt nevezzük két esemény különbségének. Jelölése: $P(A\backslash B)$, ami annyit tesz, hogy "annak valószínűsége, hogy A esemény bekövetkezik, de B nem."  

Mennyi annak a valószínűsége, hogy zöld, de nem figurás lapot húzunk?
A 8 zöld lap közül 4 figurás és 4 nem. Most csak ez utóbbiak jók nekünk.
$$P(Z\backslash F)=\frac{4}{32}=0,125$$
Mennyi annak a valószínűsége, hogy figurás, de nem zöld lapot húzunk?  
A 16 figurás lap közül 4 zöld, tehát nekünk csak 12 jó most.  
$$P(F\backslash Z)=\frac{12}{32}=0,375$$

Ennek kiszámítása általánosan:  
$$P(A\backslash B)=P(A)-P(A*B)$$
Ezzel kapcsolatban fontos látni, hogy ez az első olyan művelet, amely nem kommutatív, tehát mint fent is láthatják, $P(A\backslash B)\ne P(B\backslash A)$.  
Emellett fontos lehet, hogy ebben a kontextusban a "de" és az "és" egyenértékű, ezért a fentieket felhasználva kétféleképpen jelölhetjük ugyanazt az összetett eseményt: $P(A\backslash B)=P(A*\bar{B})$  

## De Morgan-azonosságok

Akárcsak az egyszerű eseményeknek, úgy az összetett eseményenkek is van komplementerük. A kísérlet legyen az, hogy embereket megkérdezünk, beszélnek-e angolul és hogy beszélnek-e franciául. Jelölje `A` esemény, hogy valaki beszél angolul, és `F`, hogy beszél franciául. Ebben az esetben `A*F` jelöli, hogy mindkét nyelven beszél, és `A+F`, hogy legalább egyik nyelven beszél.  

Annak, hogy valaki mindkét nyelven beszél, az a komplementere, hogy legfeljebb egyik nyelven beszél (ami egyenértékű azzal, hogy nem beszél mindkét nyelven). Ez körülírható úgy is, hogy "nem beszél angolul vagy nem beszél franciául". A kétféle megfogalmazást a szokásos jelöléssel így írhatnánk:  
Nem igaz, hogy mindkét nyelven beszél: $P(\overline{A*F})$, illetve nem beszél angolul vagy nem beszél franciául: $P(\bar{A}+\bar{F})$. Mivel mindkettő ugyanazt a nyelvtudást jelöli, egyenlőségjelet tehetünk közé. Általánosan:  
$$P(\overline{A*B})=P(\bar{A}+\bar{B})$$  

Annak, hogy valaki legalább egyik nyelven beszél ($P(A+F)$), a komplementere ($P(\overline{A+F})$)), hogy egyik nyelven sem beszél, vagy másképpen, hogy nem beszél angolul és nem beszél franciául sem ($P(\bar{A}*\bar{F})$. Általánosan:  
$$P(\overline{A+B})=P(\bar{A}*\bar{B})$$  

Ezek az ún. **de Morgan-azonosságok**. Ezek segítségével a $P(\bar{A}*\bar{B})$ és $P(\bar{A}+\bar{B})$ eseményeket át tudjuk írni a másik alakra, amelyre alkalmazni tudjuk a komplementerszabályt:  
$$P(\bar{A}+\bar{B})=P(\overline{A*B})=1-P(A*B)$$
$$P(\bar{A}*\bar{B})=P(\overline{A+B})=1-P(A+B)$$  

